In [1]:
import common_functions as cf
import common_trade_signals as cts
import pandas as pd

indices = ['^ixic', '^GSPC', '^DJI', '^NYA', '^FTSE', '^HSI', '^GDAXI', '^FCHI', 'BTC-USD', 'EURUSD=X']
return_stats = pd.DataFrame(
    columns=['Index', 'Buy & Hold Return [%]', 'Return [%]'])

for index in indices:
    tradingData = cf.read_data(index, '1y', '1h')
    cf.set_indicators(tradingData, 200)
    cf.set_trade_signals(tradingData, cts.total_macd_trade_signal)
    backtest, stats, heatmap = cf.backtest_trading(tradingData, 25000)

    return_stats = pd.concat([
        return_stats,
        pd.DataFrame([[index, stats.loc['Buy & Hold Return [%]'], stats.loc['Return [%]']]], columns=[
                     'Index', 'Buy & Hold Return [%]', 'Return [%]'])
    ], ignore_index=True)


return_stats

100%|██████████| 1756/1756 [00:00<00:00, 7139.16it/s]
100%|██████████| 1756/1756 [00:00<00:00, 4939.15it/s]
100%|██████████| 1756/1756 [00:00<00:00, 153803.70it/s]
100%|██████████| 1756/1756 [00:00<00:00, 223296.08it/s]
100%|██████████| 1756/1756 [00:00<00:00, 151341.75it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 127

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

/var/folders/rk/xympl3kj42nf5b5zvnt_lrxh0000gn/T/ipykernel_61180/2061942165.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return_stats = pd.concat([
100%|██████████| 1749/1749 [00:00<00:00, 9702.44it/s]
100%|██████████| 1749/1749 [00:00<00:00, 5742.98it/s]
100%|██████████| 1749/1749 [00:00<00:00, 153421.26it/s]
100%|██████████| 1749/1749 [00:00<00:00, 157739.60it/s]
100%|██████████| 1749/1749 [00:00<00:00, 120453.15it/s]

number of trades: 117

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 7370.44it/s]
100%|██████████| 1749/1749 [00:00<00:00, 6044.48it/s]
100%|██████████| 1749/1749 [00:00<00:00, 160799.58it/s]
100%|██████████| 1749/1749 [00:00<00:00, 222628.68it/s]
100%|██████████| 1749/1749 [00:00<00:00, 148144.87it/s]

number of trades: 107

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 9151.94it/s]
100%|██████████| 1749/1749 [00:00<00:00, 4938.87it/s]
100%|██████████| 1749/1749 [00:00<00:00, 138786.49it/s]
100%|██████████| 1749/1749 [00:00<00:00, 193905.63it/s]
100%|██████████| 1749/1749 [00:00<00:00, 132286.90it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 110

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2258/2258 [00:00<00:00, 9631.66it/s]
100%|██████████| 2258/2258 [00:00<00:00, 5295.10it/s]
100%|██████████| 2258/2258 [00:00<00:00, 80165.38it/s]
100%|██████████| 2258/2258 [00:00<00:00, 96051.14it/s]
100%|██████████| 2258/2258 [00:00<00:00, 12265.14it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 153

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1706/1706 [00:00<00:00, 10718.11it/s]
100%|██████████| 1706/1706 [00:00<00:00, 5176.25it/s]
100%|██████████| 1706/1706 [00:00<00:00, 160732.35it/s]
100%|██████████| 1706/1706 [00:00<00:00, 196110.47it/s]
100%|██████████| 1706/1706 [00:00<00:00, 141833.15it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 112

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2291/2291 [00:00<00:00, 10000.31it/s]
100%|██████████| 2291/2291 [00:00<00:00, 5878.59it/s]
100%|██████████| 2291/2291 [00:00<00:00, 149946.17it/s]
100%|██████████| 2291/2291 [00:00<00:00, 206289.05it/s]
100%|██████████| 2291/2291 [00:00<00:00, 149533.16it/s]

number of trades: 155

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2295/2295 [00:00<00:00, 8123.47it/s]
100%|██████████| 2295/2295 [00:00<00:00, 6003.92it/s]
100%|██████████| 2295/2295 [00:00<00:00, 140579.90it/s]
100%|██████████| 2295/2295 [00:00<00:00, 207764.30it/s]
100%|██████████| 2295/2295 [00:00<00:00, 135869.23it/s]

number of trades: 160

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 8755/8755 [00:01<00:00, 8750.45it/s]
100%|██████████| 8755/8755 [00:01<00:00, 4551.10it/s]
100%|██████████| 8755/8755 [00:00<00:00, 136526.02it/s]
100%|██████████| 8755/8755 [00:00<00:00, 226286.73it/s]
100%|██████████| 8755/8755 [00:00<00:00, 155550.56it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 571

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 6158/6158 [00:00<00:00, 11054.92it/s]
100%|██████████| 6158/6158 [00:01<00:00, 5998.67it/s]
100%|██████████| 6158/6158 [00:00<00:00, 61845.77it/s]
100%|██████████| 6158/6158 [00:00<00:00, 223706.87it/s]
100%|██████████| 6158/6158 [00:00<00:00, 153298.66it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 391

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

      Index  Buy & Hold Return [%]  Return [%]
0     ^ixic              31.377496   28.773014
1     ^GSPC              20.992456   11.056869
2      ^DJI              12.867031   52.560890
3      ^NYA              12.727577   24.297924
4     ^FTSE               1.547797   -1.098582
5      ^HSI             -17.553435  115.921428
6    ^GDAXI              12.515501   37.440851
7     ^FCHI               6.377608    7.623755
8   BTC-USD             125.547076  175.080326
9  EURUSD=X              -3.197864    0.000588

In [4]:
import common_functions as cf
import common_trade_signals as cts
import pandas as pd

indices = ['^ixic', '^GSPC', '^DJI', '^NYA', '^FTSE', '^HSI', '^GDAXI', '^FCHI', 'BTC-USD', 'EURUSD=X']
return_stats = pd.DataFrame(
    columns=['Index', 'Buy & Hold Return [%]', 'Return [%]'])

for index in indices:
    tradingData = cf.read_data(index, '1y', '1h')
    cf.set_indicators(tradingData, 200)
    cf.set_trade_signals(tradingData, cts.total_macd_ema_trade_signal)
    backtest, stats, heatmap = cf.backtest_trading(tradingData, 25000)

    return_stats = pd.concat([
        return_stats,
        pd.DataFrame([[index, stats.loc['Buy & Hold Return [%]'], stats.loc['Return [%]']]], columns=[
                     'Index', 'Buy & Hold Return [%]', 'Return [%]'])
    ], ignore_index=True)


return_stats

100%|██████████| 1756/1756 [00:00<00:00, 9371.63it/s]
100%|██████████| 1756/1756 [00:00<00:00, 5833.21it/s]
100%|██████████| 1756/1756 [00:00<00:00, 152387.61it/s]
100%|██████████| 1756/1756 [00:00<00:00, 198984.11it/s]
100%|██████████| 1756/1756 [00:00<00:00, 93452.75it/s]

number of trades: 44

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

/var/folders/rk/xympl3kj42nf5b5zvnt_lrxh0000gn/T/ipykernel_59698/3109507945.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return_stats = pd.concat([
100%|██████████| 1749/1749 [00:00<00:00, 8079.76it/s]
100%|██████████| 1749/1749 [00:00<00:00, 5936.89it/s]
100%|██████████| 1749/1749 [00:00<00:00, 149485.22it/s]
100%|██████████| 1749/1749 [00:00<00:00, 218569.19it/s]
100%|██████████| 1749/1749 [00:00<00:00, 84915.36it/s]

number of trades: 40

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 9732.73it/s]
100%|██████████| 1749/1749 [00:00<00:00, 5934.03it/s]
100%|██████████| 1749/1749 [00:00<00:00, 166924.65it/s]
100%|██████████| 1749/1749 [00:00<00:00, 214341.50it/s]
100%|██████████| 1749/1749 [00:00<00:00, 89244.85it/s]

number of trades: 37

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 7179.24it/s]
100%|██████████| 1749/1749 [00:00<00:00, 6060.25it/s]
100%|██████████| 1749/1749 [00:00<00:00, 154396.43it/s]
100%|██████████| 1749/1749 [00:00<00:00, 217945.80it/s]
100%|██████████| 1749/1749 [00:00<00:00, 86115.53it/s]

number of trades: 38

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2258/2258 [00:00<00:00, 8021.09it/s]
100%|██████████| 2258/2258 [00:00<00:00, 5988.91it/s]
100%|██████████| 2258/2258 [00:00<00:00, 153501.55it/s]
100%|██████████| 2258/2258 [00:00<00:00, 214863.16it/s]
100%|██████████| 2258/2258 [00:00<00:00, 68403.01it/s]

number of trades: 44

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1706/1706 [00:00<00:00, 10996.36it/s]
100%|██████████| 1706/1706 [00:00<00:00, 5867.87it/s]
100%|██████████| 1706/1706 [00:00<00:00, 154070.21it/s]
100%|██████████| 1706/1706 [00:00<00:00, 223176.43it/s]
100%|██████████| 1706/1706 [00:00<00:00, 95504.49it/s]

number of trades: 28

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2291/2291 [00:00<00:00, 9997.13it/s]
100%|██████████| 2291/2291 [00:00<00:00, 5637.57it/s]
100%|██████████| 2291/2291 [00:00<00:00, 137556.55it/s]
100%|██████████| 2291/2291 [00:00<00:00, 209532.28it/s]
100%|██████████| 2291/2291 [00:00<00:00, 78769.34it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 51

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2295/2295 [00:00<00:00, 9629.03it/s]
100%|██████████| 2295/2295 [00:00<00:00, 5570.71it/s]
100%|██████████| 2295/2295 [00:00<00:00, 153859.75it/s]
100%|██████████| 2295/2295 [00:00<00:00, 214123.63it/s]
100%|██████████| 2295/2295 [00:00<00:00, 53932.51it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 48

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 8755/8755 [00:00<00:00, 9610.89it/s]
100%|██████████| 8755/8755 [00:01<00:00, 5590.13it/s]
100%|██████████| 8755/8755 [00:00<00:00, 148619.21it/s]
100%|██████████| 8755/8755 [00:00<00:00, 194051.45it/s]
100%|██████████| 8755/8755 [00:00<00:00, 88995.25it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 197

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 6156/6156 [00:00<00:00, 10225.23it/s]
100%|██████████| 6156/6156 [00:01<00:00, 5586.81it/s]
100%|██████████| 6156/6156 [00:00<00:00, 57776.87it/s]
100%|██████████| 6156/6156 [00:00<00:00, 230284.02it/s]
100%|██████████| 6156/6156 [00:00<00:00, 96719.48it/s]

number of trades: 130

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:191: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

      Index  Buy & Hold Return [%]  Return [%]
0     ^ixic              31.377496   12.110339
1     ^GSPC              20.992456    4.511764
2      ^DJI              12.867031   27.415667
3      ^NYA              12.727577   20.074858
4     ^FTSE               1.547797   -2.840804
5      ^HSI             -17.553435    9.670283
6    ^GDAXI              12.515501   13.519869
7     ^FCHI               6.377608    4.405815
8   BTC-USD             125.547076  182.510529
9  GBPUSD=X               0.186167    0.000598

In [2]:
import common_functions as cf
import common_trade_signals as cts
import pandas as pd

indices = ['^ixic', '^GSPC', '^DJI', '^NYA', '^FTSE', '^HSI', '^GDAXI', '^FCHI', 'BTC-USD', 'EURUSD=X']
return_stats = pd.DataFrame(
    columns=['Index', 'Buy & Hold Return [%]', 'Return [%]'])

for index in indices:
    tradingData = cf.read_data(index, '1y', '1h')
    cf.set_indicators(tradingData, 200)
    cf.set_trade_signals(tradingData, cts.total_bolinger_band_signal)
    backtest, stats, heatmap = cf.backtest_trading(tradingData, 25000)

    return_stats = pd.concat([
        return_stats,
        pd.DataFrame([[index, stats.loc['Buy & Hold Return [%]'], stats.loc['Return [%]']]], columns=[
                     'Index', 'Buy & Hold Return [%]', 'Return [%]'])
    ], ignore_index=True)


return_stats

100%|██████████| 1756/1756 [00:00<00:00, 9446.15it/s]
100%|██████████| 1756/1756 [00:00<00:00, 5974.66it/s]
100%|██████████| 1756/1756 [00:00<00:00, 149129.30it/s]
100%|██████████| 1756/1756 [00:00<00:00, 226002.57it/s]
100%|██████████| 1756/1756 [00:00<00:00, 125733.17it/s]

number of trades: 199

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

/var/folders/rk/xympl3kj42nf5b5zvnt_lrxh0000gn/T/ipykernel_61180/515026509.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return_stats = pd.concat([
100%|██████████| 1749/1749 [00:00<00:00, 9448.02it/s]
100%|██████████| 1749/1749 [00:00<00:00, 4382.61it/s]
100%|██████████| 1749/1749 [00:00<00:00, 157566.80it/s]
100%|██████████| 1749/1749 [00:00<00:00, 218927.95it/s]
100%|██████████| 1749/1749 [00:00<00:00, 120056.92it/s]

number of trades: 190

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 9758.13it/s]
100%|██████████| 1749/1749 [00:00<00:00, 5952.63it/s]
100%|██████████| 1749/1749 [00:00<00:00, 151993.99it/s]
100%|██████████| 1749/1749 [00:00<00:00, 196697.62it/s]
100%|██████████| 1749/1749 [00:00<00:00, 125682.53it/s]

number of trades: 196

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1749/1749 [00:00<00:00, 7122.82it/s]
100%|██████████| 1749/1749 [00:00<00:00, 6050.58it/s]
100%|██████████| 1749/1749 [00:00<00:00, 153610.81it/s]
100%|██████████| 1749/1749 [00:00<00:00, 224056.62it/s]
100%|██████████| 1749/1749 [00:00<00:00, 125007.88it/s]

number of trades: 198

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2258/2258 [00:00<00:00, 10300.81it/s]
100%|██████████| 2258/2258 [00:00<00:00, 5235.49it/s]
100%|██████████| 2258/2258 [00:00<00:00, 157638.08it/s]
100%|██████████| 2258/2258 [00:00<00:00, 218355.62it/s]
100%|██████████| 2258/2258 [00:00<00:00, 108867.82it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 253

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 1706/1706 [00:00<00:00, 10690.50it/s]
100%|██████████| 1706/1706 [00:00<00:00, 6032.89it/s]
100%|██████████| 1706/1706 [00:00<00:00, 149962.96it/s]
100%|██████████| 1706/1706 [00:00<00:00, 181371.86it/s]
100%|██████████| 1706/1706 [00:00<00:00, 126343.83it/s]

number of trades: 196

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2291/2291 [00:00<00:00, 9892.00it/s]
100%|██████████| 2291/2291 [00:00<00:00, 5269.08it/s]
100%|██████████| 2291/2291 [00:00<00:00, 164253.37it/s]
100%|██████████| 2291/2291 [00:00<00:00, 224387.04it/s]
100%|██████████| 2291/2291 [00:00<00:00, 120796.88it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 229

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 2295/2295 [00:00<00:00, 9315.75it/s]
100%|██████████| 2295/2295 [00:00<00:00, 6090.45it/s]
100%|██████████| 2295/2295 [00:00<00:00, 157137.48it/s]
100%|██████████| 2295/2295 [00:00<00:00, 215958.71it/s]
100%|██████████| 2295/2295 [00:00<00:00, 116727.43it/s]

number of trades: 222

/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 8755/8755 [00:00<00:00, 9111.80it/s]
100%|██████████| 8755/8755 [00:01<00:00, 5989.75it/s]
100%|██████████| 8755/8755 [00:00<00:00, 159216.13it/s]
100%|██████████| 8755/8755 [00:00<00:00, 210709.18it/s]
100%|██████████| 8755/8755 [00:00<00:00, 122462.96it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  backtest = Backtest(data, MacdStrategy, cash=cash,
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 1015

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

100%|██████████| 6158/6158 [00:00<00:00, 8964.29it/s]
100%|██████████| 6158/6158 [00:01<00:00, 5771.68it/s]
100%|██████████| 6158/6158 [00:00<00:00, 135073.00it/s]
100%|██████████| 6158/6158 [00:00<00:00, 197840.89it/s]
100%|██████████| 6158/6158 [00:00<00:00, 113629.37it/s]
/Users/andrew/github/trading-strategies/ddd-southwest/common_functions.py:199: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  backtest = Backtest(data, MacdStrategy, cash=cash,

number of trades: 816

/Users/andrew/.pyenv/versions/3.11.4/lib/python3.11/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

  0%|          | 0/8 [00:00<?, ?it/s]

      Index  Buy & Hold Return [%]  Return [%]
0     ^ixic              31.377496   34.045835
1     ^GSPC              20.992456    6.978810
2      ^DJI              12.867031   25.748380
3      ^NYA              12.727577   11.048715
4     ^FTSE               1.547797   19.930329
5      ^HSI             -17.553435   26.459994
6    ^GDAXI              12.515501   27.332518
7     ^FCHI               6.377608    6.605057
8   BTC-USD             125.547076  205.284176
9  EURUSD=X              -3.197864    0.000335